apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docs
  name: docs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
      - image: chusj/cqdg-docs:6a8c69e2bad5486db37fec165d08d2289bfb2b71
        name: docs
        resources:
          requests:
            memory: "256Mi"
            cpu: '0.25'
          limits:
            memory: "512Mi"
            cpu: '0.5'
